<?php

namespace ContainerJhghuUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z4NEXMLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z4NEXML' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z4NEXML'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'message' => ['privates', '.errored..service_locator.z4NEXML.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.z4NEXML": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageUploader' => ['privates', 'App\\Service\\ImageUploader', 'getImageUploaderService', true],
        ], [
            'message' => 'App\\Entity\\Message',
            'em' => '?',
            'imageUploader' => 'App\\Service\\ImageUploader',
        ]);
    }
}
