<?php

namespace ContainerJhghuUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ImageUploader' shared autowired service.
     *
     * @return \App\Service\ImageUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ImageUploader.php';

        return $container->privates['App\\Service\\ImageUploader'] = new \App\Service\ImageUploader((\dirname(__DIR__, 4).'/public/uploads'));
    }
}
