<?php

namespace ContainerJhghuUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControlleraddMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xb9mHdy.App\Controller\MessageController::addMessage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xb9mHdy.App\\Controller\\MessageController::addMessage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageUploader' => ['privates', 'App\\Service\\ImageUploader', 'getImageUploaderService', true],
        ], [
            'em' => '?',
            'imageUploader' => 'App\\Service\\ImageUploader',
        ]))->withContext('App\\Controller\\MessageController::addMessage()', $container);
    }
}
