<?php

namespace ContainerJhghuUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllerdeleteMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z4NEXML.App\Controller\MessageController::deleteMessage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z4NEXML.App\\Controller\\MessageController::deleteMessage()'] = ($container->privates['.service_locator.z4NEXML'] ?? $container->load('get_ServiceLocator_Z4NEXMLService'))->withContext('App\\Controller\\MessageController::deleteMessage()', $container);
    }
}
