services:
  php:
    build: ./docker/php
    container_name: mini_reseau_php
    working_dir: /var/www/html
    volumes:
      - ./symfony:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  web:
    image: nginx:alpine
    container_name: mini_reseau_web
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0
    container_name: mini_reseau_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_reseau
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mini_reseau_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: mini_reseau_mailhog
    ports:
      - "8025:8025"
