<?php

namespace ContainerJYwRxUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C2u0zWbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c2u0zWb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c2u0zWb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\MessageController::displayMessages' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::displayMessages()', 'getMessageControllerdisplayMessagesService', true],
            'App\\Controller\\MessageController::displayMessageById' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::displayMessageById()', 'getMessageControllerdisplayMessageByIdService', true],
            'App\\Controller\\MessageController::addMessage' => ['privates', '.service_locator.Xb9mHdy.App\\Controller\\MessageController::addMessage()', 'getMessageControlleraddMessageService', true],
            'App\\Controller\\MessageController::deleteMessage' => ['privates', '.service_locator.ALnIiFA.App\\Controller\\MessageController::deleteMessage()', 'getMessageControllerdeleteMessageService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\MessageController:displayMessages' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::displayMessages()', 'getMessageControllerdisplayMessagesService', true],
            'App\\Controller\\MessageController:displayMessageById' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::displayMessageById()', 'getMessageControllerdisplayMessageByIdService', true],
            'App\\Controller\\MessageController:addMessage' => ['privates', '.service_locator.Xb9mHdy.App\\Controller\\MessageController::addMessage()', 'getMessageControlleraddMessageService', true],
            'App\\Controller\\MessageController:deleteMessage' => ['privates', '.service_locator.ALnIiFA.App\\Controller\\MessageController::deleteMessage()', 'getMessageControllerdeleteMessageService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\MessageController::displayMessages' => '?',
            'App\\Controller\\MessageController::displayMessageById' => '?',
            'App\\Controller\\MessageController::addMessage' => '?',
            'App\\Controller\\MessageController::deleteMessage' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\MessageController:displayMessages' => '?',
            'App\\Controller\\MessageController:displayMessageById' => '?',
            'App\\Controller\\MessageController:addMessage' => '?',
            'App\\Controller\\MessageController:deleteMessage' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:register' => '?',
        ]);
    }
}
