<?php

namespace ContainerJYwRxUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllerdeleteMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ALnIiFA.App\Controller\MessageController::deleteMessage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ALnIiFA.App\\Controller\\MessageController::deleteMessage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'imageUploader' => ['privates', 'App\\Service\\ImageUploader', NULL, 'Cannot autowire service "App\\Service\\ImageUploader": argument "$uploadDir" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'imageUploader' => 'App\\Service\\ImageUploader',
            'em' => '?',
        ]))->withContext('App\\Controller\\MessageController::deleteMessage()', $container);
    }
}
