<?php

namespace ContainerDnQmaTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sk5EQMCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sk5EQMC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sk5EQMC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\CommentController::listMessages' => ['privates', '.service_locator..zbb2WU.App\\Controller\\CommentController::listMessages()', 'getCommentControllerlistMessagesService', true],
            'App\\Controller\\CommentController::addMessage' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CommentController::addMessage()', 'getCommentControlleraddMessageService', true],
            'App\\Controller\\CommentController::editMessage' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::editMessage()', 'getCommentControllereditMessageService', true],
            'App\\Controller\\CommentController::deleteMessage' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::deleteMessage()', 'getCommentControllerdeleteMessageService', true],
            'App\\Controller\\DefaultController::home' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\DefaultController::home()', 'getDefaultControllerhomeService', true],
            'App\\Controller\\MessageController::listMessages' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::listMessages()', 'getMessageControllerlistMessagesService', true],
            'App\\Controller\\MessageController::addMessage' => ['privates', '.service_locator.Xb9mHdy.App\\Controller\\MessageController::addMessage()', 'getMessageControlleraddMessageService', true],
            'App\\Controller\\MessageController::editMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::editMessage()', 'getMessageControllereditMessageService', true],
            'App\\Controller\\MessageController::deleteMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::deleteMessage()', 'getMessageControllerdeleteMessageService', true],
            'App\\Controller\\MessageController::showMessage' => ['privates', '.service_locator.a3g.CnQ.App\\Controller\\MessageController::showMessage()', 'getMessageControllershowMessageService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\CommentController:listMessages' => ['privates', '.service_locator..zbb2WU.App\\Controller\\CommentController::listMessages()', 'getCommentControllerlistMessagesService', true],
            'App\\Controller\\CommentController:addMessage' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\CommentController::addMessage()', 'getCommentControlleraddMessageService', true],
            'App\\Controller\\CommentController:editMessage' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::editMessage()', 'getCommentControllereditMessageService', true],
            'App\\Controller\\CommentController:deleteMessage' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::deleteMessage()', 'getCommentControllerdeleteMessageService', true],
            'App\\Controller\\DefaultController:home' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\DefaultController::home()', 'getDefaultControllerhomeService', true],
            'App\\Controller\\MessageController:listMessages' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::listMessages()', 'getMessageControllerlistMessagesService', true],
            'App\\Controller\\MessageController:addMessage' => ['privates', '.service_locator.Xb9mHdy.App\\Controller\\MessageController::addMessage()', 'getMessageControlleraddMessageService', true],
            'App\\Controller\\MessageController:editMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::editMessage()', 'getMessageControllereditMessageService', true],
            'App\\Controller\\MessageController:deleteMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::deleteMessage()', 'getMessageControllerdeleteMessageService', true],
            'App\\Controller\\MessageController:showMessage' => ['privates', '.service_locator.a3g.CnQ.App\\Controller\\MessageController::showMessage()', 'getMessageControllershowMessageService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\CommentController::listMessages' => '?',
            'App\\Controller\\CommentController::addMessage' => '?',
            'App\\Controller\\CommentController::editMessage' => '?',
            'App\\Controller\\CommentController::deleteMessage' => '?',
            'App\\Controller\\DefaultController::home' => '?',
            'App\\Controller\\MessageController::listMessages' => '?',
            'App\\Controller\\MessageController::addMessage' => '?',
            'App\\Controller\\MessageController::editMessage' => '?',
            'App\\Controller\\MessageController::deleteMessage' => '?',
            'App\\Controller\\MessageController::showMessage' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\CommentController:listMessages' => '?',
            'App\\Controller\\CommentController:addMessage' => '?',
            'App\\Controller\\CommentController:editMessage' => '?',
            'App\\Controller\\CommentController:deleteMessage' => '?',
            'App\\Controller\\DefaultController:home' => '?',
            'App\\Controller\\MessageController:listMessages' => '?',
            'App\\Controller\\MessageController:addMessage' => '?',
            'App\\Controller\\MessageController:editMessage' => '?',
            'App\\Controller\\MessageController:deleteMessage' => '?',
            'App\\Controller\\MessageController:showMessage' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:register' => '?',
        ]);
    }
}
