<?php

namespace ContainerDnQmaTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllerlistMessagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..zbb2WU.App\Controller\CommentController::listMessages()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..zbb2WU.App\\Controller\\CommentController::listMessages()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
        ]))->withContext('App\\Controller\\CommentController::listMessages()', $container);
    }
}
