<?php

namespace ContainerDnQmaTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllerdeleteMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aCnRYOo.App\Controller\CommentController::deleteMessage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aCnRYOo.App\\Controller\\CommentController::deleteMessage()'] = ($container->privates['.service_locator.aCnRYOo'] ?? $container->load('get_ServiceLocator_ACnRYOoService'))->withContext('App\\Controller\\CommentController::deleteMessage()', $container);
    }
}
