<?php

namespace ContainerDnQmaTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllereditMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z4NEXML.App\Controller\MessageController::editMessage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.z4NEXML'] ?? $container->load('get_ServiceLocator_Z4NEXMLService'));

        if (isset($container->privates['.service_locator.z4NEXML.App\\Controller\\MessageController::editMessage()'])) {
            return $container->privates['.service_locator.z4NEXML.App\\Controller\\MessageController::editMessage()'];
        }

        return $container->privates['.service_locator.z4NEXML.App\\Controller\\MessageController::editMessage()'] = $a->withContext('App\\Controller\\MessageController::editMessage()', $container);
    }
}
