<?php

namespace ContainerDnQmaTt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllershowMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a3g.CnQ.App\Controller\MessageController::showMessage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a3g.CnQ.App\\Controller\\MessageController::showMessage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'message' => ['privates', '.errored..service_locator.a3g.CnQ.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.a3g.CnQ": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".'],
        ], [
            'message' => 'App\\Entity\\Message',
        ]))->withContext('App\\Controller\\MessageController::showMessage()', $container);
    }
}
