<?php

namespace Container5H972Aa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XyVmABXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xyVmABX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xyVmABX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\CommentController::editComment' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::editComment()', 'getCommentControllereditCommentService', true],
            'App\\Controller\\CommentController::deleteComment' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::deleteComment()', 'getCommentControllerdeleteCommentService', true],
            'App\\Controller\\DefaultController::home' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\DefaultController::home()', 'getDefaultControllerhomeService', true],
            'App\\Controller\\MessageController::listMessages' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::listMessages()', 'getMessageControllerlistMessagesService', true],
            'App\\Controller\\MessageController::addMessage' => ['privates', '.service_locator.Xb9mHdy.App\\Controller\\MessageController::addMessage()', 'getMessageControlleraddMessageService', true],
            'App\\Controller\\MessageController::editMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::editMessage()', 'getMessageControllereditMessageService', true],
            'App\\Controller\\MessageController::deleteMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::deleteMessage()', 'getMessageControllerdeleteMessageService', true],
            'App\\Controller\\MessageController::showMessage' => ['privates', '.service_locator.ewkxUgM.App\\Controller\\MessageController::showMessage()', 'getMessageControllershowMessageService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\CommentController:editComment' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::editComment()', 'getCommentControllereditCommentService', true],
            'App\\Controller\\CommentController:deleteComment' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\CommentController::deleteComment()', 'getCommentControllerdeleteCommentService', true],
            'App\\Controller\\DefaultController:home' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\DefaultController::home()', 'getDefaultControllerhomeService', true],
            'App\\Controller\\MessageController:listMessages' => ['privates', '.service_locator.LJyXIf_.App\\Controller\\MessageController::listMessages()', 'getMessageControllerlistMessagesService', true],
            'App\\Controller\\MessageController:addMessage' => ['privates', '.service_locator.Xb9mHdy.App\\Controller\\MessageController::addMessage()', 'getMessageControlleraddMessageService', true],
            'App\\Controller\\MessageController:editMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::editMessage()', 'getMessageControllereditMessageService', true],
            'App\\Controller\\MessageController:deleteMessage' => ['privates', '.service_locator.z4NEXML.App\\Controller\\MessageController::deleteMessage()', 'getMessageControllerdeleteMessageService', true],
            'App\\Controller\\MessageController:showMessage' => ['privates', '.service_locator.ewkxUgM.App\\Controller\\MessageController::showMessage()', 'getMessageControllershowMessageService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\CommentController::editComment' => '?',
            'App\\Controller\\CommentController::deleteComment' => '?',
            'App\\Controller\\DefaultController::home' => '?',
            'App\\Controller\\MessageController::listMessages' => '?',
            'App\\Controller\\MessageController::addMessage' => '?',
            'App\\Controller\\MessageController::editMessage' => '?',
            'App\\Controller\\MessageController::deleteMessage' => '?',
            'App\\Controller\\MessageController::showMessage' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\CommentController:editComment' => '?',
            'App\\Controller\\CommentController:deleteComment' => '?',
            'App\\Controller\\DefaultController:home' => '?',
            'App\\Controller\\MessageController:listMessages' => '?',
            'App\\Controller\\MessageController:addMessage' => '?',
            'App\\Controller\\MessageController:editMessage' => '?',
            'App\\Controller\\MessageController:deleteMessage' => '?',
            'App\\Controller\\MessageController:showMessage' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:register' => '?',
        ]);
    }
}
