<?php

namespace Container5H972Aa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllereditCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aCnRYOo.App\Controller\CommentController::editComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.aCnRYOo'] ?? $container->load('get_ServiceLocator_ACnRYOoService'));

        if (isset($container->privates['.service_locator.aCnRYOo.App\\Controller\\CommentController::editComment()'])) {
            return $container->privates['.service_locator.aCnRYOo.App\\Controller\\CommentController::editComment()'];
        }

        return $container->privates['.service_locator.aCnRYOo.App\\Controller\\CommentController::editComment()'] = $a->withContext('App\\Controller\\CommentController::editComment()', $container);
    }
}
