<?php

namespace Container5H972Aa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageControllerlistMessagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LJyXIf_.App\Controller\MessageController::listMessages()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LJyXIf_.App\\Controller\\MessageController::listMessages()'] = ($container->privates['.service_locator.LJyXIf_'] ?? $container->load('get_ServiceLocator_LJyXIfService'))->withContext('App\\Controller\\MessageController::listMessages()', $container);
    }
}
