# config/services.yaml

parameters:
    # Dossier où seront stockées les images uploadées
    upload_dir: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true      # injecte automatiquement les dépendances
        autoconfigure: true # ajoute automatiquement les tags nécessaires
        public: false

    # autowire tous les controllers
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # autowire le reste des services dans src/
    App\:
        resource: '../src/'
        exclude: '../src/{Entity,Migrations,Tests}'

    # Service ImageUploader avec injection du chemin des uploads
    App\Service\ImageUploader:
        arguments:
            $uploadDir: '%upload_dir%'
